apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "2"
  generation: 1
  name: commerce-yr-gateway-v2
  namespace: commerce-yr
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-yr-gateway
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: commerce-yr-gateway
        version: v2
    spec:
      containers:
      - image: 192.168.100.12/commerce-yr/commerce-yr-gateway-img:apig-1
        imagePullPolicy: Always
        name: commerce-yr-gateway-v2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30